// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLbKvxZ6PMChhvuhBdcE-ebstuJXNBgt8',
    appId: '1:1064211507761:web:570e37254f094d0e240310',
    messagingSenderId: '1064211507761',
    projectId: 'fir-weather-6cdae',
    authDomain: 'fir-weather-6cdae.firebaseapp.com',
    storageBucket: 'fir-weather-6cdae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBarBbnmGwYm7qXEGE_P6_t19HhzSwj3PY',
    appId: '1:1064211507761:android:be9ecfa61aea5d3e240310',
    messagingSenderId: '1064211507761',
    projectId: 'fir-weather-6cdae',
    storageBucket: 'fir-weather-6cdae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKmGojQIZABpGYdQXblybKv_u303yZb4c',
    appId: '1:1064211507761:ios:ef77b91ed9486f3b240310',
    messagingSenderId: '1064211507761',
    projectId: 'fir-weather-6cdae',
    storageBucket: 'fir-weather-6cdae.appspot.com',
    iosBundleId: 'com.example.jhonRhayParrenoTechnicalAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKmGojQIZABpGYdQXblybKv_u303yZb4c',
    appId: '1:1064211507761:ios:ef77b91ed9486f3b240310',
    messagingSenderId: '1064211507761',
    projectId: 'fir-weather-6cdae',
    storageBucket: 'fir-weather-6cdae.appspot.com',
    iosBundleId: 'com.example.jhonRhayParrenoTechnicalAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLbKvxZ6PMChhvuhBdcE-ebstuJXNBgt8',
    appId: '1:1064211507761:web:962043f84e1b685e240310',
    messagingSenderId: '1064211507761',
    projectId: 'fir-weather-6cdae',
    authDomain: 'fir-weather-6cdae.firebaseapp.com',
    storageBucket: 'fir-weather-6cdae.appspot.com',
  );
}
